### ISSUE TITLE
Reserve balance during DAO creation

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/elio-dao-protocol#10]
To prevent users from spamming up DAOs, they have to make a deposit in XLM upon creating a new DAO. This deposit remains locked up until the DAO is destroyed.

For this to work, the user must allow the DAO contract to withdraw the funds from their wallet.

**Comment by deepink-mas** [comment]
Interacting with lumen needs Stellar Asset Contract which is made simpler with https://github.com/stellar/rs-soroban-sdk/pull/912 (which requires rust-1.69).

**Comment by deep-ink-ventures** [comment]
Note as well that the id need to be unique.
