### ISSUE TITLE
Implement proposal creation

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/elio-dao-protocol#3]
When a new proposal is created, the protocol should generate a globally unique (*not* per-DAO unique) identifier for the proposal.

**Comment by deepink-mas** [comment]
Having a globally unique identifier only seems useful if we store proposals in a global (Hash)Map. But the idea to limit proposals to a maximum amount per DAO naturally leads to a design using cyclic buffers (currently mocked with Vec).

If we have a cyclic buffer per DAO, then we only need an index into that, (besides the DAO id to get to the buffer). Of course you can take the view that the globally unique identifier in this case *is* the combination of DAO id and index into cyclic buffer.

**Comment by deep-ink-ventures** [comment]
We are *not* limiting the maximum amount. We are limiting the maximum amount of *active* proposals. The current implementation is really only to get the `assets` contract to work.

**Comment by deepink-mas** [comment]
Okay, so we need old proposals to persist instead of being overwritten if we use a cyclic buffer, is what you're saying?

**Comment by deep-ink-ventures** [comment]
i'm not sure what you mean by cyclic buffer. 

Similar to how we store [here](https://github.com/deep-ink-ventures/elio-dao-protocol/blob/main/contracts/assets/src/types.rs#L28) checkpoints per address we need to store proposals per DAO.

Secondly we need to check that not more than `25` of them are active. That is to slice off the last `25` proposals from a DAO and check that the oldest one (they are added in order) is not active. If it is active then we can't add a new one.

Third, we need to make sure that `get_active_proposals` only returns the active ones, that is from the slice above cut off from the beginning until only active ones remain.

Fourth, we need a global incrementor, that is assigned as the proposal id everytime a new proposal is added.

There might be other ways to do it, but this one seems straightforward to me.
