### ISSUE TITLE
One should only be allowed to vote once, but can update afterwards

### ISSUE THREAD

**Issue by deep-ink-ventures** [deep-ink-ventures/elio-dao-protocol#54]
For obvious reasons :-)

We need to track the voter for a given proposal. The best way for this is a Double enum key, sth like

```
pub enum VotingHistory {
    Voting(Address, u32)
}
```

That we set to true upon voting, so that if the key does NOT exist one can vote for the first time.

If the key exists, one can only change their vote: If it's `false` and the user changes to `true`, we reduce `against` and move the votes to `in_favor` - and vice versa.

If someone votes `true` while already `true` or `false` when already `false` we error with `VoteAlreadyCast`

**Comment by deep-ink-ventures** [comment]
That's a good one. I'll update the ticket.

**Comment by deepink-pat** [comment]
Would voting power change over time? 

If yes, What if the voting power when some voted was 100 and by the time they updated their vote their voting power became 200. Would it be possible for me to get the old voting power so I can subtract the proper amount?

**Comment by deep-ink-ventures** [comment]
No, the voting power is constant for a given proposal; that's the idea of checkpoints. `voting_power` is always the balance BEFORE the proposal was created.
