### ISSUE TITLE
Add additional hookpoints.

### ISSUE THREAD

**Issue by deep-ink-ventures** [deep-ink-ventures/elio-dao-protocol#58]
Add the following hookpoints, create a hooks.rs for them and adjust the test case in the `hookpoints` contracts to alter all outputs for testing.

## Core Contract

`before_destroy_dao(dao_id)`

Does nothing, but the underlying contract may panic with error.

---

`before_change_owner(dao_id)`

Does nothing, but the underlying contract may panic with error.

## Votes Contract

`before_proposal_creation(dao_id, proposal_owner)` 

Does nothing, but the underlying contract may panic with error.

---

`before_set_metadata(dao_id, proposal_id, meta, hash, proposal_owner)`

Does nothing, but the underlying contract may panic with error.

---

`set_configuration(env, dao_id, proposal_duration, proposal_token_deposit) -> proposal_duration, proposal_token_deposit`

use the duration and deposit returned from the function; should default to the given duration / deposit

---

`before_fault_proposal(dao_id, proposal_id, reason)`

Does nothing, but the underlying contract may panic with error.

---

`before_finalize_proposal(dao_id, proposal_id)`

Does nothing, but the underlying contract may panic with error.

---

`before_mark_implemented(propsoal_id)`

Does nothing, but the underlying contract may panic with error.

## Assets Contract 

`incr_allowance(from, spender, amount)` -> amount
`decr_allowance(from, spender, amount)` -> amount
`xfer(from, to, amount)` -> amount
`xfer(from, spender, from, to, amount)` -> amount

Use the returned amount as incr/decr/xfer/xfer_from, default to amount

**Comment by deepink-pat** [comment]
duplicate `xfer` function on the description. Did you mean `xfer_from` for the second one?

**Comment by deep-ink-ventures** [comment]
yep!

**Comment by deepink-pat** [comment]
Isn't `dao_id` a necessary parameter for all the functions? Since each hookpoint call need to check whether the hookpoint exist. Such example would be for `before_mark_implemented`. It only takes a `proposal_id` as a parameter. The same could be said for assets contract hookpoints.

**Comment by deepink-pat** [comment]
should I remove `proposal_token_deposit` for the function `set_configuration`?

**Comment by deep-ink-ventures** [comment]
> Isn't dao_id a necessary parameter for all the functions? 

Not really, because the hookpoint contract is already per dao, so it should be clear. Actually we don't need it anywhere.


> should I remove proposal_token_deposit for the function set_configuration?
Yep.
