### ISSUE TITLE
Fix all #ignored tests

### ISSUE THREAD

**Issue by deep-ink-ventures** [deep-ink-ventures/elio-dao-protocol#68]

**Comment by deepink-pat** [comment]
Test cases included in PR #64 and #65 are ignored for now due to limitations of preview 10 that error codes should be limited to single digit. Should I create a new Error contract in the mean to remove the ignore in these test cases?

**Comment by deep-ink-ventures** [comment]
The error code errors are fine, leave them at ignore, but make a comment.
