### ISSUE TITLE
Record checkpoint

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/elio-dao-protocol#8]
Whenever we register a change in token balance, we will capture a snapshot of a wallet's total balance at that specific point in time. To avoid growing an ever-increasing amount of checkpoints, we also must perform some housekeeping according to the rules below:

tbd

**Comment by deep-ink-ventures** [comment]
https://github.com/deep-ink-ventures/elio-dao-protocol/blob/wip/contracts/assets/src/types.rs#L31-L36

**Comment by deep-ink-ventures** [comment]
Prepped here: https://github.com/deep-ink-ventures/elio-dao-protocol/blob/main/contracts/assets/src/types.rs#L59-L65
