### ISSUE TITLE
Get balance at checkpoint

### ISSUE THREAD

**Issue by x-xo** [deep-ink-ventures/elio-dao-protocol#9]
To calculate a wallet's voting power, we must be able to retrieve their balance at a specific time/block, by evaluating their last checkpoint either at the exact block, or earlier.

Here is an example:
- A wallet has received tokens at block 90
- A proposal has been created at block 95
- To get the voting power for the wallet on the proposal, we must evaluate the balance at block 95, or earlier (90 in this case)

If we cannot find a checkpoint, the voting power defaults to 0.

**Comment by deep-ink-ventures** [comment]
Reopening this as the checkpoint tests fail. Currently they are all ignored.

**Comment by deepink-pat** [comment]
https://github.com/deep-ink-ventures/elio-dao-protocol/pull/63

Already submitted a PR for this. Should have associated it in this ticket. Mb
